name: macOS Software Update List and Version Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update-macos-versions:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run softwareupdate command
        run: |
          softwareupdate --list-full-installers > list.txt

      - name: Extract latest versions
        run: |
          # list.txt에서 OS 명칭과 버전 추출
          awk -F', ' '/^* Title:/ {
              split($1, a, ": ");
              split($2, b, ": ");
              print a[2], b[2];
          }' list.txt > temp.txt
          
          # temp.txt에서 각 OS의 최신 버전만 남기기
          awk '{
              split($2, ver, ".");
              version = ver[1] * 1000000 + ver[2] * 1000 + ver[3];
              if (version > max[$1] || !($1 in max)) {
                  max[$1] = version;
                  latest[$1] = $2;
              }
          }
          END {
              for (os in latest) {
                  print os, latest[os];
              }
          }' temp.txt | sort -k1,1 -k2,2nr > temp2.txt && mv temp2.txt latest_versions.txt        

      #- name: Update PowerShell script
      #  run: |
      #    sed -i '' -E 's/(macOSVersions\s*=\s*@\().*(\))/\1'"$(cat latest_versions.txt | tr '\n' ',' | sed 's/,$//')"'\2/' macos_down.ps1

      #- name: Update Shell script
      #  run: |
      #    sed -i '' -E 's/(macOSVersions=\().*(\))/\1'"$(cat latest_versions.txt | tr '\n' ' ' | sed 's/ $//')"'\2/' macos_down.sh

      #- name: Commit and push changes
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add list.txt latest_versions.txt macos_down.ps1 macos_down.sh
      #    git commit -m "Update macOS versions and scripts"
      #    git push

      - name: Upload files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: updated-files
          path: |
            list.txt
            latest_versions.txt
            #macos_down.ps1
            #macos_down.sh
