name: macOS Software Update List and Version Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update-macos-versions:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run softwareupdate command
        run: |
          softwareupdate --list-full-installers | grep macOS | awk -F', ' '/^* Title:/ {split($1, a, ": ");
              split($2, b, ": ");
              print a[2], b[2];
          }' > list.txt

          cat ./list.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract latest versions
        run: |
          python3 - <<EOF
          import re
          from collections import defaultdict

          def extract_latest_versions(input_file, output_file):
              versions = defaultdict(lambda: [0, ''])
              
              with open(input_file, 'r') as f:
                  for line in f:
                      match = re.match(r'(macOS \w+) (\d+(?:\.\d+)*)', line.strip())
                      if match:
                          os, version = match.groups()
                          version_tuple = tuple(map(int, version.split('.')))
                          if version_tuple > tuple(map(int, versions[os][1].split('.'))):
                              versions[os] = [version_tuple, version]
              
              with open(output_file, 'w') as f:
                  for os in sorted(versions.keys()):
                      f.write(f"{os} {versions[os][1]}\n")

          extract_latest_versions('list.txt', 'latest_versions.txt')
          EOF

          cat ./latest_versions.txt

      - name: Upload files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: updated-files
          path: |
            list.txt
            latest_versions.txt
