name: macOS Software Update List and Version Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행

jobs:
  update-macos-versions:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run softwareupdate command
        run: |
          softwareupdate --list-full-installers > list.txt

      - name: Extract latest versions
        run: |
          awk '/^macOS/ {
            split($2, v, ".");
            version = v[1] "." v[2];
            if ($NF > latest[version] || !(version in latest)) {
              latest[version] = $NF;
            }
          }
          END {
            for (v in latest) {
              print v, latest[v];
            }
          }' list.txt | sort -V > latest_versions.txt

      #- name: Update PowerShell script
      #  run: |
      #    sed -i '' -E 's/(macOSVersions\s*=\s*@\().*(\))/\1'"$(cat latest_versions.txt | tr '\n' ',' | sed 's/,$//')"'\2/' macos_down.ps1

      #- name: Update Shell script
      #  run: |
      #    sed -i '' -E 's/(macOSVersions=\().*(\))/\1'"$(cat latest_versions.txt | tr '\n' ' ' | sed 's/ $//')"'\2/' macos_down.sh

      #- name: Commit and push changes
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add list.txt latest_versions.txt macos_down.ps1 macos_down.sh
      #    git commit -m "Update macOS versions and scripts"
      #    git push

      - name: Upload files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: updated-files
          path: |
            list.txt
            latest_versions.txt
            #macos_down.ps1
            #macos_down.sh
